# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{action_sms_gateways}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Wilkie"]
  s.date = %q{2010-10-15}
  s.email = %q{dwilkie@gmail.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "action_sms_gateways.gemspec",
     "lib/action_sms_gateways.rb",
     "lib/action_sms_gateways/connection_adapters.rb",
     "lib/action_sms_gateways/connection_adapters/sms_global.rb",
     "lib/action_sms_gateways/connection_adapters/test_helpers/sms_global.rb",
     "lib/action_sms_gateways/connection_adapters/test_helpers/tropo.rb",
     "lib/action_sms_gateways/connection_adapters/tropo.rb",
     "spec/connection_adapters/sms_global_spec.rb",
     "spec/connection_adapters/tropo_spec.rb",
     "spec/spec_helper.rb",
     "todo"
  ]
  s.homepage = %q{http://github.com/dwilkie/action_sms_gateways}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{SMS Gateway Adapters to use with action_sms}
  s.test_files = [
    "spec/connection_adapters/sms_global_spec.rb",
     "spec/connection_adapters/tropo_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tropo_message>, [">= 0"])
    else
      s.add_dependency(%q<tropo_message>, [">= 0"])
    end
  else
    s.add_dependency(%q<tropo_message>, [">= 0"])
  end
end

